services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures 服务仅在开发环境使用
  Tourze\StockManageBundle\DataFixtures\:
    resource: '../../DataFixtures/*'
    tags: ['doctrine.fixture.orm']